-- Kalabsha Airlines database foundation
create extension if not exists pgcrypto;

create type public.pilot_status as enum (
  'pending',
  'active',
  'suspended',
  'retired'
);

create type public.user_role as enum (
  'pilot',
  'dispatcher',
  'staff',
  'admin'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  pilot_number integer generated by default as identity (start with 1),
  callsign text generated always as ('KVA-P' || lpad(pilot_number::text, 3, '0')) stored,
  full_name text not null,
  country_code text,
  role public.user_role not null default 'pilot',
  status public.pilot_status not null default 'pending',
  total_hours numeric(10,2) not null default 0,
  total_flights integer not null default 0,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (pilot_number),
  unique (callsign)
);

create table public.aircraft (
  id uuid primary key default gen_random_uuid(),
  registration text not null unique,
  type_code text not null,
  model text not null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table public.routes (
  id uuid primary key default gen_random_uuid(),
  flight_number text not null unique,
  departure_icao text not null,
  arrival_icao text not null,
  aircraft_type text not null,
  scheduled_minutes integer,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.pireps (
  id uuid primary key default gen_random_uuid(),
  pirep_number bigint generated by default as identity (start with 1),
  pirep_code text generated always as (
    'PR-' || extract(year from created_at)::int::text || '-' ||
    lpad(pirep_number::text, 6, '0')
  ) stored,
  pilot_id uuid not null references public.profiles(id),
  route_id uuid references public.routes(id),
  flight_number text not null,
  departure_icao text not null,
  arrival_icao text not null,
  aircraft_registration text,
  block_minutes integer not null,
  status text not null default 'submitted',
  remarks text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id),
  unique (pirep_number),
  unique (pirep_code)
);

alter table public.profiles enable row level security;
alter table public.aircraft enable row level security;
alter table public.routes enable row level security;
alter table public.pireps enable row level security;

create policy "Users can read own profile"
on public.profiles for select
using (auth.uid() = id);

create policy "Users can update own basic profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Authenticated users can read aircraft"
on public.aircraft for select
to authenticated
using (true);

create policy "Authenticated users can read routes"
on public.routes for select
to authenticated
using (active = true);

create policy "Pilots can read own pireps"
on public.pireps for select
using (auth.uid() = pilot_id);

create policy "Pilots can submit own pireps"
on public.pireps for insert
with check (auth.uid() = pilot_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
